### ISSUE TITLE
Skip freezing in production?

### ISSUE THREAD

**Issue by epeli** [aearly/icepick#10]
Using `process.env.NODE_ENV` like in seamless-immutable

https://github.com/rtfeldman/seamless-immutable/blob/6ec4f557f1f8bc86e1b1897cf24e72c956794f63/src/seamless-immutable.js#L68-L78

Which is usable in browsers too with Browserify and Webpack.

Would make production builds faster.

**Comment by aearly** [comment]
:+1:  Seems pretty straightforward.  When bundling icepick for the browser, currently you have to use Browserify or Webpack, so relying on `process.env.NODE_ENV` (like React does) is a good strategy.  Most people are using `envify` (or the webpack equivalent) to strip out the React dev stuff, so not freezing in production mode would follow.


There's something nagging me in the back of my mind, because I remember thinking about this 6 months ago, but I cant remember why I didn't choose to do this at that time.
